version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: cache
    ports:
      - 5432:5432
