version: '3'

services:
  postgres:
    image: postgres:14.7
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cache
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      retries: 5
      timeout: 5s
    ports:
      - "5432:5432"
